import { MantineProvider, mantineHtmlProps } from "@mantine/core";
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import { Header } from "@/components/layouts/Header";
import { Toaster } from "@/components/ui/sonner";
import { theme } from "@/constants/theme";
import { cn } from "@/lib/utils";
import "../styles/globals.css";

const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "MedReserve",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      {...mantineHtmlProps}
      className={cn("font-sans", geist.variable)}
    >
      <head></head>
      <body className={`demo antialiased`}>
        <MantineProvider theme={theme}>
          <Header />
          <main style={{ paddingTop: "56px" }}>
            {children}
            <Toaster richColors />
          </main>
        </MantineProvider>
      </body>
    </html>
  );
}
