import { MantineProvider, mantineHtmlProps } from "@mantine/core";
import type { Metadata } from "next";
import { theme } from "@/constants/theme";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "MedReserve",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head></head>
      <body className={`demo antialiased`}>
        <MantineProvider theme={theme}>{children}</MantineProvider>
      </body>
    </html>
  );
}
